version: "3"
services:
  tasks-api:
    build: ./tasks-api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_CONNECTION_URI=mongodb://admin:password@mongo:27017/admin
    networks:
      - mongo-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - mongo-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongodata:/data/db
networks:
  mongo-network:
volumes:
  mongodata:

