apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-tls
  namespace: default
spec:
  secretName: frontend-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: tasks.com
  dnsNames:
    - tasks.com
