apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: high-permission-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: high-permission-sa
    namespace: default
roleRef:
  kind: Role
  name: high-permission-role
  apiGroup: rbac.authorization.k8s.io
