apiVersion: v1
kind: Service
metadata:
  name: tasks-api
  labels:
    app: tasks-api
spec:
  type: {{ .Values.tasksApi.service.type }}
  ports:
    - port: {{ .Values.tasksApi.service.port }}
      targetPort: {{ .Values.tasksApi.service.port }}
      # nodePort: {{ .Values.tasksApi.service.nodePort }}
  selector:
    app: tasks-api
