apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tasks-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tasks-api
  minReplicas: 1  # min replicas
  maxReplicas: 5  # max replicas
  targetCPUUtilizationPercentage: 30
