replicaCount: 1

frontend:
  image:
    repository: zengqhh/frontend
    tag: 2.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080
  resources: {}

tasksApi:
  image:
    repository: zengqhh/tasks-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    # nodePort: 30001
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "200m"

mongo:
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
